services:
  crypto-scout-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-scout-client:0.0.1
    container_name: crypto-scout-client
    restart: unless-stopped
    # Expose HTTP health endpoint
    ports:
      - "8080:8080"
    # If you change server.port in application.properties, update the ports mapping accordingly.
    # Secrets file is provided for your deployment workflow convenience, but the app reads
    # configuration from src/main/resources/application.properties at build time.
    # To change config, edit that file and rebuild the image.
    env_file:
      - secret/client.env
    networks:
      - crypto-scout-bridge
    # Harden container
    read_only: true
    tmpfs:
      - /tmp:rw,size=64m,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "10001:10001"

networks:
  crypto-scout-bridge:
    name: crypto-scout-bridge
    external: true