services:
  crypto-scout-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-scout-client:0.0.1
    container_name: crypto-scout-client
    cpus: "1.00"
    memory: 1G
    env_file:
      - secret/client.env
    environment:
      TZ: UTC
    networks:
      - crypto-scout-bridge
    ports:
      - "8081:8081"
    security_opt:
      - no-new-privileges=true
    read_only: true
    tmpfs:
      - /tmp:rw,size=64m,mode=1777,nodev,nosuid
    cap_drop:
      - ALL
    user: "10001:10001"
    init: true
    pids_limit: 256
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: unless-stopped
    stop_signal: SIGTERM
    stop_grace_period: 30s
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/ready || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

networks:
  crypto-scout-bridge:
    name: crypto-scout-bridge
    external: true