services:
  crypto-scout-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-scout-client:0.0.1
    container_name: crypto-scout-client
    cpus: "1.00"
    memory: 1G
    env_file:
      - secret/client.env
    environment:
      TZ: UTC
    networks:
      - crypto-scout-bridge
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges=true
    read_only: true
    tmpfs:
      - /tmp:rw,size=64m,mode=1777
    cap_drop:
      - ALL
    user: "10001:10001"
    restart: unless-stopped
    stop_grace_period: 30s
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

networks:
  crypto-scout-bridge:
    name: crypto-scout-bridge
    external: true